add_newline = true

format = """
â•­â”€$username@$hostname $directory$git_branch$git_status$kubernetes$terraform$python
â•°â”€$character """

# Username
[username]
style_user = "green"
show_always = true
format = "[$user]($style)"

# Hostname
[hostname]
ssh_only = false
style = "green"
format = "[$hostname]($style)"

# Directory
[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style) "

# Git branch
[git_branch]
symbol = "ğŸŒ± "
style = "cyan"
format = "[$symbol$branch]($style) "

# Git status
[git_status]
style = "red"
format = "[$all_status$ahead_behind]($style) "
conflicted = "="
stashed    = "$"
modified   = "!"
staged     = "+"
untracked  = "?"
renamed    = "Â»"
deleted    = "âœ˜"
ahead      = "â‡¡${count}"
behind     = "â‡£${count}"

# Kubernetes
[kubernetes]
symbol = "â˜¸ï¸ "
style = "yellow"
format = "[$symbol$context]($style) "

# Terraform
[terraform]
symbol = "ğŸ’  "
style = "magenta"
format = "[$symbol$workspace]($style) "

# Python
[python]
symbol = "ğŸ "
style = "red"
format = "[$symbol$version]($style) "

# Prompt character (arrow)
[character]
success_symbol = "[â¤](bold green)"
error_symbol   = "[â¤](bold red)"
